# Generated by Django 3.0.14 on 2025-06-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='orientacion',
            new_name='detalles',
        ),
    ]
