# Generated by Django 3.0.14 on 2025-06-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250611_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
