# Generated by Django 3.0.14 on 2025-07-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserva_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_responsable', to='core.Pasajero')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.GrupoReserva'),
        ),
    ]
